In [1]:
from fiberamp.fiber.microstruct.bragg import Bragg
from fiberamp.fiber import sellmeier
from ngsolve.webgui import Draw
import ngsolve as ng
import numpy as np

importing NGSolve-6.2.2203-56-g47f483033


In [2]:
n_air = 1.00027717
n_glass = 1.4388164768221814

In [3]:
d = 15*2/3*1e-6
ts=[15*2.7183333333333333e-6, d, 15*1e-6, 15*1e-6, 15*1e-6]
ns=[lambda x: n_air, lambda x: n_glass, lambda x: n_air, lambda x: n_glass, lambda x: n_glass]
maxhs=[.1, .015, .04, .04, .1]
scale=15e-6

$\lambda_m = \frac{2 n_1 d}{m} \big[ (n_2 / n_1)^2 - 1 \big]^{1/2}$

In [4]:
B = Bragg(ts=ts, scale=scale, maxhs=maxhs, ns=ns, wl=.5*ts[0])

ModeSolver: Checking if mesh has required regions
Mesh has  18378  elements,  9226  points,  and  27603  edges.


In [5]:
spikes = np.array([2*n_air * d / m * ((n_glass/n_air)**2 - 1)**.5 for m in range(1, 18)])

In [6]:
spikes, B.wavelength

(array([2.06846652e-05, 1.03423326e-05, 6.89488840e-06, 5.17116630e-06,
        4.13693304e-06, 3.44744420e-06, 2.95495217e-06, 2.58558315e-06,
        2.29829613e-06, 2.06846652e-06, 1.88042411e-06, 1.72372210e-06,
        1.59112809e-06, 1.47747609e-06, 1.37897768e-06, 1.29279158e-06,
        1.21674501e-06]),
 2.03875e-05)

In [7]:
Draw(B.index, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

BaseWebGuiScene

In [8]:
ks = np.array(B.refractive_indices) * B.L * B.k
guess = min(ks)

guess

4.624103115377935

In [9]:
B.L**2 * B.k**2 * (B.n0**2 - n_air**2) +  guess

27.48279151313755

In [65]:
23.14284569-0.06112482j, 23.14245714-0.06130243j

((23.14284569-0.06112482j), (23.14245714-0.06130243j))

In [79]:
# Center, radius and span
center = 23.14245714-0.06130243j
radius = .01
nspan = 2
npts = 2
p = 1

In [80]:
beta, zs, Es1, phis1,_ = B.leakyvecmodes(p=p, ctr=center, rad=radius,
                                       alpha=10, d=2,
#                                        rhoinv=.99,
#                                        quadrule='ellipse_trapez_shift',
                                       nspan=nspan, npts=npts,
                                       niterations=5, nrestarts=0,
                                       stop_tol=1e-11)

Set NGSolve custom (smooth) PML with alpha= 10 degree= 2 and thickness=1.000
Set custom smoothed PML with d= 2  alpha= 10 and thickness=1.000
Using FEAST to search for vector leaky modes in
circle of radius 0.01 centered at  (23.14245714-0.06130243j)
assuming not more than 2 modes in this interval
System size: 91962  x  91962   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.01, Center=23.1425-0.0613024j
SpectralProjNGR:   Making resolvent at z = +23.142 -0.051j
SpectralProjNGR:   Making resolvent at z = +23.142 -0.071j

=========== Starting FEAST iterations ===========
Trying with 2 vectors:

 ITERATION 1 with 2 vectors and 2 left vectors
   During kernel cleaning abs(g):
   [0.  0.1]
   Real part of computed eigenvalues:
   [23.14881272 23.14901136]
   Imag part of computed eigenvalues:
   [-0.06121375 -0.06361997]
   Relative Hausdorff distance from prior iterate: 4.319e+98

 ITERATION 2 with 2 vectors and 2

In [83]:
for e in Es1:
#     Draw(e.real, B.mesh, vectors={'grid_size':200})
    Draw(e.Norm(), B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [82]:
for phi1 in phis1:
    Draw(phi1, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

# Less smooth PML

In [212]:
beta, zs, Es2, phis2,_ = B.leakyvecmodes(p=p, ctr=center, rad=radius,
                                       alpha=8, d=1,
#                                        rhoinv=.99,
#                                        quadrule='ellipse_trapez_shift',
                                       nspan=nspan, npts=npts,
                                       niterations=4, nrestarts=0,
                                       stop_tol=1e-11)

Set NGSolve custom (smooth) PML with alpha= 8 degree= 1 and thickness=3.000
Set custom smoothed PML with d= 1  alpha= 8 and thickness=3.000
Using FEAST to search for vector leaky modes in
circle of radius 0.001 centered at  (6.218853153319084-0.0030889077490732822j)
assuming not more than 4 modes in this interval
System size: 202107  x  202107   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.001, Center=6.21885-0.00308891j
SpectralProjNGR:   Making resolvent at z =  +6.220 -0.002j
SpectralProjNGR:   Making resolvent at z =  +6.218 -0.002j
SpectralProjNGR:   Making resolvent at z =  +6.218 -0.004j
SpectralProjNGR:   Making resolvent at z =  +6.220 -0.004j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [4.4e-21 1.8e-23 4.5e-24 5.2e-24]
   Real part of computed eigenvalues:
   [5.75924742 6.36198561 6.4

In [197]:
for e in Es2:
    Draw(e.real, B.mesh, vectors={'grid_size':200})

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [216]:
for phi in phis2:
    Draw(ng.grad(phi).Norm(), B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

# Discontinuous PML

In [214]:
beta, zs, Es3, phis3,_ = B.leakyvecmodes(p=p, ctr=center, rad=radius,
                                       alpha=8,
#                                        rhoinv=.99,
#                                        quadrule='ellipse_trapez_shift',
                                       nspan=nspan, npts=npts,
                                       niterations=4, nrestarts=0,
                                       stop_tol=1e-11)

Set NGSolve automatic PML with alpha= 8 and thickness=3.000
Using FEAST to search for vector leaky modes in
circle of radius 0.001 centered at  (6.218853153319084-0.0030889077490732822j)
assuming not more than 4 modes in this interval
System size: 202107  x  202107   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.001, Center=6.21885-0.00308891j
SpectralProjNGR:   Making resolvent at z =  +6.220 -0.002j
SpectralProjNGR:   Making resolvent at z =  +6.218 -0.002j
SpectralProjNGR:   Making resolvent at z =  +6.218 -0.004j
SpectralProjNGR:   Making resolvent at z =  +6.220 -0.004j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [5.6e-21 1.5e-23 2.0e-24 6.0e-24]
   Real part of computed eigenvalues:
   [5.88790071 6.38761512 6.59502668 6.69921638]
   Imag part of computed eigenvalues:
   [-0.77559274 -0.334

In [200]:
for e in Es3:
    Draw(e.real, B.mesh, vectors={'grid_size':200})

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [215]:
for phi in phis3:
    Draw(ng.grad(phi).Norm(), B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…