In [1]:
from fiberamp.fiber.microstruct.bragg import Bragg
from fiberamp.fiber import sellmeier
from ngsolve.webgui import Draw
import ngsolve as ng
import numpy as np

importing NGSolve-6.2.2203-56-g47f483033


In [14]:
n_air = 1.00027717
n_glass = 1.4388164768221814
n_poly = 1.6-.3j

In [15]:
ts = [4.0775e-05, 1e-5, 1.5e-5, 2.5e-5, 4e-5]
ns = [lambda x: n_air, lambda x: n_glass, lambda x: n_poly, lambda x: n_air, lambda x: n_air]
mats = ['air', 'glass', 'poly', 'air', 'Outer']
maxhs = [.1, .02, .03, .05, .08]
scale = 1.5e-5

In [16]:
B = Bragg(ts=ts, scale=scale, mats=mats, maxhs=maxhs, ns=ns, fan=True, wl=3.6e-6)

ModeSolver: Checking if mesh has required regions
Mesh has  13152  elements,  6660  points,  and  19811  edges.


In [17]:
Draw(B.index, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

BaseWebGuiScene

In [18]:
k_low = B.ns[0](B.wavelength) * B.k * B.scale

In [19]:
beta = .9995 * k_low

In [20]:
exact = B.sqrZfrom(beta/B.L)

In [21]:
guess = exact.conjugate()
guess

0.6855977435237719

In [26]:
center = guess
radius = .5
nspan = 4
npts = 2
p = 3

In [27]:
beta, zs, Es, phis,_ = B.leakyvecmodes(p=p, ctr=center, rad=radius,
                                       alpha=6,
#                                        rhoinv=.9,
#                                        quadrule='ellipse_trapez_shift',
                                       nspan=nspan, npts=npts,
                                       niterations=5, nrestarts=0,
                                       stop_tol=1e-11)

Set NGSolve automatic PML with alpha= 6 and thickness=2.667
Using FEAST to search for vector leaky modes in
circle of radius 0.5 centered at  0.6855977435237719
assuming not more than 4 modes in this interval
System size: 237068  x  237068   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.5, Center=0.685598+0j
SpectralProjNGR:   Making resolvent at z =  +0.686 +0.500j
SpectralProjNGR:   Making resolvent at z =  +0.686 -0.500j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [22.5  0.3  0.3  0.7]
   Real part of computed eigenvalues:
   [-0.74880053  0.1152368   0.16342401  0.77329222]
   Imag part of computed eigenvalues:
   [ 1.93317734e+00  3.87346400e-04 -8.46381092e-01 -7.46045744e-02]
   Relative Hausdorff distance from prior iterate: 1.459e+100

 ITERATION 2 with 4 vectors and 4 left vectors
   Du

In [28]:
for e in Es:
    Draw(e.real, B.mesh, vectors={'grid_size' : 200})

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [30]:
for phi in phis:
    Draw(1e2*phi, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…