In [1]:
from fiberamp.fiber.microstruct.bragg import Bragg
from fiberamp.fiber import sellmeier
from ngsolve.webgui import Draw
import ngsolve as ng
import numpy as np

importing NGSolve-6.2.2203-56-g47f483033


In [2]:
n_air = 1.00027717
n_glass = 1.4388164768221814

In [49]:
ts=[4.0775e-05, 1e-5, 1.5e-5, 1.5e-5]
ns=[lambda x: n_air, lambda x: n_glass, lambda x: n_air, lambda x: n_air]
maxhs=[.1, .02, .08, .1]
scale=15e-6

In [50]:
goodwl = 1.6999999999999998e-06
goodbeta = 55.44793711650212-1.5343515969487227e-05j

badwl = 1.72372210e-06
badbeta = 54.63752396621695-0.010762057602262157j

trial = 'good'

if trial == 'good':
    wl = goodwl
    beta = goodbeta
elif trial == 'bad':
    wl = badwl
    beta = badbeta
else:
    raise ValueError

In [51]:
B = Bragg(ts=ts, scale=scale, maxhs=maxhs, ns=ns, wl=wl)

ModeSolver: Checking if mesh has required regions
Mesh has  9603  elements,  4831  points,  and  14433  edges.


In [52]:
Draw(B.index, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

BaseWebGuiScene

In [53]:
exact = B.sqrZfrom(beta/B.L)

In [55]:
guess = exact.conjugate()
guess

(0.8095388073497816-0.0017015326172443476j)

In [56]:
center = guess
radius = .1
nspan = 4
npts = 2
p = 1

In [57]:
betas, zs, Es, phis,_ = B.leakyvecmodes(p=p, ctr=center, rad=radius,
                                       alpha=5,
#                                        rhoinv=.9,
#                                        quadrule='ellipse_trapez_shift',
                                       nspan=nspan, npts=npts,
                                       niterations=6, nrestarts=0,
                                       stop_tol=1e-9)

Set NGSolve automatic PML with p= 1  alpha= 5 and thickness=1.000
Using FEAST to search for vector leaky modes in
circle of radius 0.1 centered at  (0.8095388073497816-0.0017015326172443476j)
assuming not more than 4 modes in this interval
System size: 48072  x  48072   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.1, Center=0.809539-0.00170153j
SpectralProjNGR:   Making resolvent at z =  +0.810 +0.098j
SpectralProjNGR:   Making resolvent at z =  +0.810 -0.102j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [1.5e+00 1.5e-01 2.0e-03 8.3e-05]
   Real part of computed eigenvalues:
   [-2.91448243  0.77496371  0.77580974  1.87964997]
   Imag part of computed eigenvalues:
   [-5.86227766e-01  9.26522071e-04 -1.60122610e-03  1.71519374e+00]
   Relative Hausdorff distance from prior iterate: 1.099e+100

 I

In [58]:
for e in Es:
    Draw(e.real, B.mesh, vectors={'grid_size' : 200})

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [59]:
for phi in phis:
    Draw(1e1*phi, B.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…