# N1 Numerical Modes


In [1]:
from fiberamp.fiber.microstruct.bragg import Bragg
from fiberamp.fiber import sellmeier
from ngsolve.webgui import Draw
import ngsolve as ng
import numpy as np

In [2]:
n_air = 1.00027717
n_glass = 1.4388164768221814

In [39]:
ts=[4.0775e-05, 1e-5, 1.5e-5, 1.5e-5]
ns=[lambda x: n_air, lambda x: n_glass, lambda x: n_air, lambda x: n_air]
maxhs=[.3, .02, .08, .1]
scale=15e-6

## Mode at Antiresonant (Good) Wavelength

In [40]:
goodwl = 1.6999999999999998e-06
goodbeta = 55.44793711650212-1.5343515969487227e-05j

badwl = 1.72372210e-06
badbeta = 54.63752396621695-0.010762057602262157j

trial = 'good'

if trial == 'good':
    wl = goodwl
    beta = goodbeta
elif trial == 'bad':
    wl = badwl
    beta = badbeta
else:
    raise ValueError

In [41]:
B = Bragg(ts=ts, scale=scale, maxhs=maxhs, ns=ns, wl=wl)

Boundary names not provided, using default names.
ModeSolver: Checking if mesh has required regions
Mesh has  9367  elements,  4713  points,  and  14079  edges.


In [42]:
Draw(B.index, B.mesh)

WebGuiWidget(layout=Layout(height='50vh', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.23…

BaseWebGuiScene

In [43]:
exact = B.sqrZfrom(beta/B.L)

In [44]:
guess = exact.conjugate()
guess

(0.8095388073497816-0.0017015326172443476j)

In [45]:
center = guess
radius = .1
nspan = 4
npts = 2
p = 1

In [46]:
betas, zs, Es, phis,_ = B.leakyvecmodes(p=p, ctr=center, rad=radius,
                                       alpha=5,
#                                        rhoinv=.9,
#                                        quadrule='ellipse_trapez_shift',
                                       nspan=nspan, npts=2,
                                       niterations=6, nrestarts=0,
                                       stop_tol=1e-9)

Set NGSolve automatic PML with p= 1  alpha= 5 and thickness=1.000
Using FEAST to search for vector leaky modes in
circle of radius 0.1 centered at  (0.8095388073497816-0.0017015326172443476j)
assuming not more than 4 modes in this interval
System size: 46892  x  46892   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.1, Center=0.809539-0.00170153j
SpectralProjNGR:   Making resolvent at z =  +0.810 +0.098j
SpectralProjNGR:   Making resolvent at z =  +0.810 -0.102j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [4.9e-01 1.7e-01 8.5e-05 2.9e-03]
   Real part of computed eigenvalues:
   [-0.24689808  0.77434702  0.77630099  1.68757851]
   Imag part of computed eigenvalues:
   [ 1.25131839e+00 -1.02265192e-03 -1.35384912e-03  2.34129213e+00]
   Relative Hausdorff distance from prior iterate: 1.099e+100

 I

In [50]:
for e in Es:
    Draw(10*e.Norm(), B.mesh)

WebGuiWidget(layout=Layout(height='50vh', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.23…

WebGuiWidget(layout=Layout(height='50vh', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.23…

In [51]:
for phi in phis:
    Draw(10*phi.Norm(), B.mesh)

WebGuiWidget(layout=Layout(height='50vh', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.23…

WebGuiWidget(layout=Layout(height='50vh', width='100%'), value={'gui_settings': {}, 'ngsolve_version': '6.2.23…