
# Debug hand pml in modesolver

In [1]:
import numpy as np

from fiberamp.fiber.microstruct.bragg import Bragg
from ngsolve.webgui import Draw
from ngsolve import CF, x, y


importing NGSolve-6.2.2203-56-g47f483033


In [2]:
n_air = 1.00027717
n_glass = 1.4388164768221814
ts = [15*2.7183333333333333e-6, 15*2/3*1e-6, 15*1e-6]
ns = [lambda x: n_air, lambda x: n_glass, lambda x: n_glass]
mats = ['air', 'glass', 'Outer']
maxhs = [.1, .015, .04]
scale = 15e-6
i=0
wls = np.linspace(1.4, 2, 301) * 1e-6

A = Bragg(ts=ts, scale=scale, maxhs=maxhs, ns=ns, mats=mats, wl=wls[i])


ModeSolver: Checking if mesh has required regions
Mesh has  15936  elements,  8047  points,  and  23982  edges.


In [4]:
A.Rout - A.R

1.0

In [5]:
exact_scaled_betas = np.load('/home/pv/local/convergence/bragg_fiber/wavelength/N0/exact_scaled_betas.npy')
centers = A.sqrZfrom(exact_scaled_betas.conjugate()/A.L)

In [7]:
alpha = 2
nspan = 4
p = 2
center = centers[i]
radius = .1
npts = 2

beta, _, Es, phis, _ = A.leakyvecmodes(ctr=center,
                                       rad=radius,
                                       alpha=alpha,
                                       d=2,
                                       nspan=nspan,
                                       npts=npts,
                                       p=p,
                                       niterations=4,
                                       nrestarts=0,
                                       stop_tol=1e-9,
                                       handpml=True,
                                      )

Set handmade custom (smooth) PML with alpha =2 , and smoothing factor = 2
Using FEAST to search for vector leaky modes in
circle of radius 0.1 centered at  (4848.342367014139-0.012689514720893767j)
assuming not more than 4 modes in this interval
System size: 167562  x  167562   Inverse type: umfpack

SpectralProj: Setting shifted trapezoidal rule quadrature on circular contour
SpectralProj: Radius=0.1, Center=4848.34-0.0126895j
SpectralProjNGR:   Making resolvent at z = +4848.342 +0.087j
SpectralProjNGR:   Making resolvent at z = +4848.342 -0.113j

=========== Starting FEAST iterations ===========
Trying with 4 vectors:

 ITERATION 1 with 4 vectors and 4 left vectors
   During kernel cleaning abs(g):
   [6.3e-01 7.1e-02 1.1e-02 6.2e-06]
   Real part of computed eigenvalues:
   [4848.34176697 4848.34207308 4849.54231013 4849.86916977]
   Imag part of computed eigenvalues:
   [-0.01231879 -0.01233228 -0.04028122 -0.03585034]
   Relative Hausdorff distance from prior iterate: 2.063e+96

 

alpha = 2
p = 2

NgPML built in

Results:
 Z²: [4848.34218715-0.01203137j 4848.34220258-0.01195844j]
 beta: [4488846.18338835+5.95618047j 4488846.17575022+5.920078j  ]
 CL dB/m: [51.73472623 51.42114415]
 
NGpml custom d=0 (should give almost same as built in) (does, but differs at lower p values)

Results:
 Z²: [4848.34218715-0.01203137j 4848.34220258-0.01195844j]
 beta: [4488846.18338831+5.95618047j 4488846.17575017+5.920078j  ]
 CL dB/m: [51.73472623 51.42114415]
 
Hand Built PML

d = 0
Results:
 Z²: [4848.34230367-0.01166206j 4848.34232812-0.01159829j]
 beta: [4488846.12570202+5.77334967j 4488846.11359853+5.74178267j]
 CL dB/m: [50.14667806 49.87249061]
 
d = 1
Results:
 Z²: [4848.34201349-0.01224288j 4848.34197047-0.01224701j]
 beta: [4488846.26935885+6.06088868j 4488846.29065362+6.06293385j]
 CL dB/m: [52.64421015 52.66197431]

d = 2
Results:
 Z²: [4848.34158145-0.012311j   4848.34202282-0.01234938j]
 beta: [4488846.48324065+6.09461067j 4488846.26473777+6.11361387j]
 CL dB/m: [52.9371157  53.10217537]

In [5]:
for e in Es:
    Draw(-1e2*e.real[0],A.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

In [6]:
for phi in phis:
    Draw(1e1*phi, A.mesh)

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…

WebGuiWidget(value={'ngsolve_version': '6.2.2203-56-g47f483033', 'mesh_dim': 2, 'order2d': 2, 'order3d': 2, 'd…